version: 2
anchors:  
jobs:
  test:
    machine:
      image: ubuntu-2004:202111-01
    steps: 
      - run: 
          name: Installing prerequiste
          command: |
            sudo apt-get install ansible
      - run:
          name: executing ansible playbook
          command: |
            ansible-playbook test.yml

workflows:
  version: 2
  build:
    jobs:
      - test