version: 2
anchors:  
jobs:
  test:
    orbs: 
      ansible: orbss/ansible@0.2.3
    # steps: 
    #   # - run: 
    #   #     name: Installing prerequiste
    #   #     command: |
    #   #       sudo apt-get install ansible
    #   - run:
    #       name: executing ansible playbook
    #       working_directory:  /home/circleci/
    #       command: |
    #         pwd
    #         ls -lart
    steps:
      - run:
          name: Show Ansible version
          command: ansible --version
      - run:
          name: Execute Ansible Playbook
          command: |
            cd $CIRCLE_WORKING_DIRECTORY
            ansible-playbook -i localhost test.yml
      - run:
          name: 'Execute Ansible Playbook again, checking to make sure it''s idempotent.'
          command: |
            cd $CIRCLE_WORKING_DIRECTORY
            ansible-playbook -i localhost test.yml



workflows:
  version: 2
  build:
    jobs:
      - test