version: 2
anchors:  
jobs:
  test:
    machine:
      image: ubuntu-2004:current
    steps: 
      - run: 
          name: Installing prerequiste
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            pip3 install ansible
            pwd
            ll -lart


workflows:
  version: 2
  build:
    jobs:
      - test