version: 2
anchors:  
jobs:
  test:
    docker:
      - image: 'tomonorimatsumura/centos7-ansible:yum'
    steps: 
      # - run: 
      #     name: Installing prerequiste
      #     command: |
      #       sudo apt-get install ansible
      - run:
          name: executing ansible playbook
          command: |
            ansible-playbook ../test.yml

workflows:
  version: 2
  build:
    jobs:
      - test